### ISSUE TITLE
Funcionamento estranho da aplicação

### ISSUE THREAD

**Issue by msc6272** [cami-la/desafio-poo-java-kotlin-11-05-2023#1]
Olá Camila, tudo bem?

Estou tendo um problema estranho quando vou testar os endpoints em /api/credit. Não importa o que eu use para realizar os testes (Postman, REST Cli ou qualquer browser), a resposta que obtenho é sempre o erro 404. Eu tenho a impressão de que seja algum erro na configuração ou alguma falha do Tomcat, pois inclui uma linha para exibir uma mensagem no console, nos arquivos CreditResource.kt e CustomerResource.kt.

Antes disso, eu já havia revisto todo o código mais de 5 vezes e não encontrei nenhum erro. O Build funciona sem problemas e eu consigo executar o JAR sem nenhuma mensagem de erro.

Na função saveCustomer (CustomerResource.kt) eu coloquei como primeira linha o seguinte código: System.out.println("CustomerResource.kt -> Save Customer"). Ele aparece no terminal sempre que eu insiro um novo Customer.

De forma similar, eu inseri a linha System.out.println("CreditResource.kt -> Save Credit") na função saveCredit (CreditResource.kt). Ela NUNCA aparece no terminal e faz todo sentido, já que o erro é 404 (Not found), demonstrando que o Tomcat não conseguiu encontrar a URI do POST.

Inclusive, já tentei alterar o PATH na anotação @RequestMapping do arquivo CreditResource.kt, mas de nada adiantou (claro que alterei também no teste de acesso ao endpoint).

De alguma forma, parece que o Tomcat desconhece ou desconsidera o conteúdo da anotação RequestMapping("/api/credit"). Pode até ser algum problema durante o BUILD da aplicação. Se quiser, posso enviar meu código fonte zipado e/ou o arquivo JAR gerado. Eu digitei todo o código apresentado nas aulas. Tudo, exceto o que se refere a CREDIT funciona; inclusive os novos tratamentos de erro.

De qualquer modo, vou pesquisar sobre essa anotação e sobre algum outro problema que possa advir do meu ambiente de desenvolvimento. O estranho é que em outros códigos com API nunca tive nenhum problema similar a esse.

Perdi horas tentando encontrar a origem do problema, mas não obtive sucesso. Por acaso você não teria alguma ideia?

Muito obrigado!

**Comment by msc6272** [comment]
Olá, Camila.

Depois de "dormir com o problema" pensei em verificar as instruções IMPORT e PACKAGE. Por alguma razão, lembrei que meu ambiente é bem experimental, já que uso o VSCode com algumas extensões que não são tão confiáveis: Kotlin Language from mathiasfrohlich e Kotlin from fwcd.

Bingo! O problema é que essa extensões não fazem um bom trabalho em validar o código. No meu caso, uma letra a mais em algumas instruções package e import geraram o problema.

Ao invés de package dio.bootcamp.tqi.kotlin.creditrequestsystem.controller, eu tinha package dio.bootcamp.tqi.kotlin.creditresquestsystem.controller. Ao invés de import dio.bootcamp.tqi.kotlin.creditrequestsystem.dto.CreditView eu tinha import dio.bootcamp.tqi.kotlin.creditresquestsystem.dto.CreditView. Tudo porque as extensões (ainda não sei qual delas) não criam o "molde" das classes Kotlin, ao contrário do que as extensões de Java do VSCode fazem. Como eu mesmo tive que popular o arquivo de classe Kotlin com as instruções package, eu cometi alguns erros de digitação. E como nem sempre as extensões sugeriam o FIX para uma classe referenciada, eu tive que inserir manualmente. Claro que todo esse processo manual pode gerar erros.

Para mim, o compilador falhou também, pois não indicou o erro em relação à instrução package. De qualquer modo, acabei encontrando o problema. Muito obrigado, mesmo assim. Espero que isso possa servir para outros colegas que utilizam o VSCode.

**Comment by cami-la** [comment]
Agradeço pela solução do problema, @msc6272.
Assim, caso algum colega tenha a mesma dúvida que você, eu consigo ajudar com mais facilidade.

Confesso que não utilizo o Vs Code para desenvolvimento Java ou Kotlin, prefiro o IntelliJ ou Eclipse (para Java).

Mas enfim, bons estudos para nós! (:
